### ISSUE TITLE
remove archive button if data is already archived

### ISSUE THREAD

**Issue by kitchell** [brain-life/core-warehouse#22]
Currently I cannot tell if a data set has already been archived

**Comment by kitchell** [comment]
well, It does show that for one of the data sets I archived, but not for another. It may be that the first data set I tried did not actually archive.

**Comment by kitchell** [comment]
once I refreshed the "see archived data link" disappeared.

**Comment by soichih** [comment]
I tried to recreate this, but I couldn't. I've made substantial changes yesterday on data provisioning and archiving part, so it's possible that some kind of backward incompatibility has caused it. Can you re-run the task again?

**Comment by kitchell** [comment]
when I go to the process page, all finished apps still have the option to archive their data even though they have already been archived. When I click archive, the green archive button disappears and it now says see archived dataset. When I refresh the page, it goes back to showing the green archive button again.

**Comment by soichih** [comment]
Currently, I am using task.config to store the archive status. The ability to update the task is meant for admin, so I need to find a different way to do this. 

I am planning to introduce a new collection to store all data provenance information. Most likely, this issue need to be fully resolved as part of that update.
