### ISSUE TITLE
boolean input choices

### ISSUE THREAD

**Issue by kitchell** [brain-life/core-warehouse#36]
For the normalize data app, the boolean inputs are asking for a typed response instead of a box to check. I think the check box that was there before was better, or if it is going to be typed there should be a description somewhere on the interface explaining what the options are (true or false) otherwise users may type incorrect inputs (e.g. yes, no, TRUE, FALSE).

**Comment by soichih** [comment]
Note to myself. This issue happens on dynamic processing page (not the simple process submission form)

**Comment by soichih** [comment]
@kitchell I believe I've fixed this issue. Please try again and see if it's fixed for you. Thank you for reporting this issue!

**Comment by kitchell** [comment]
it looks fixed for me! Thanks!
