### ISSUE TITLE
show existing brainlife tags when adding tags to an input/output datatype 

### ISSUE THREAD

**Issue by kitchell** [brain-life/core-warehouse#43]
It would be nice if the existing tags that are currently used on brainlife would show up as options to choose from when a user is trying to add a tag to an input or output datatype or other file. I wanted to add the tag acpc_aligned to an input T1 for an app, but could not remember how it was written (with or without _ ?). If it showed up as a clickable option below, we could avoid typos and other small tagging mistakes.

**Comment by soichih** [comment]
Implemented. Please test.

The control looks strange - because it's competing stylesheet with vue/element which I am planning to replace with something else (bootstrap4)
