### ISSUE TITLE
keep track of tags on input data when process is processing

### ISSUE THREAD

**Issue by kitchell** [brain-life/core-warehouse#44]
We should indicate somewhere the tags of the input data for a process once it starts/finish processing. Right now it does not indicate if the dwi.nii.gz file is single shell, normalized, etc. once a process begins. It is easy to accidentally choose a non-normalized/non-single shell file by accident, and once a process begins it is impossible to distinguish which one you chose.

**Comment by soichih** [comment]
I've updated the process page. Please let me know what you think - and see if I've added tags in the right places.

**Comment by kitchell** [comment]
perfect! both the numbers and the tags will be very helpful.
