### ISSUE TITLE
improve dataset selection page

### ISSUE THREAD

**Issue by kitchell** [brain-life/core-warehouse#69]
With the addition of multiple tags on the HCP dataset, when you select one of the datasets (e.g. dwi) and the panel on the right of the page appears showing what you have selected, the page listing the data scrolls up/down so that the data set you selected is out of view. It is moving because the tags are now on a second line for the anat data and the height of the anat entry has to increase. This probably depends on screen size, but it is happening on my laptop. It is very annoying. I wonder if it is possible to prevent it from moving?

**Comment by soichih** [comment]
I think I know what you mean, but can you copy / paste the screenshot just to be sure?

**Comment by kitchell** [comment]
![screen shot 2017-07-28 at 11 48 20 am](https://user-images.githubusercontent.com/25829572/28725227-db4cc4d6-738a-11e7-9552-98f364356589.png)
first image is before I click on anything, second image is after I click on freesurfer data for 111211. 
![screen shot 2017-07-28 at 11 48 35 am](https://user-images.githubusercontent.com/25829572/28725278-f9ef44ea-738a-11e7-9bcf-7a2fa2757009.png)

**Comment by kitchell** [comment]
the data set I clicked on is not visible and now I have to scroll again and find it. not a huge deal, but it gets annoying.

**Comment by soichih** [comment]
I agree that this is super annoying.

Easiest thing to do is always have an empty select list displayed so that it won't influence the table width when you select a first item - but then it reduces the screen estate unnecessarily.. 

I will see if I can somehow preserve the screen position - maybe even through CSS..

**Comment by soichih** [comment]
The fix has been released to production. Please refresh the page and try again.

**Comment by kitchell** [comment]
awesome. its fixed!
